[tool.poetry]
name = "mesop-apps"
version = "0.1.0"
description = ""
authors = ["Brendan Hills <brendanhills@google.com>"]
readme = "README.md"
packages = [{include = "mesop_apps"}]

[tool.poetry.dependencies]
python = "^3.11"
mesop = "^0.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
