[project]
name = "loan-approval-agent"
version = "0.1.0"
description = "AI-driven agent designed to automate loan approval decisions"
authors = [{ name = "Brendan Hills", email = "brendanhills@google.com" }]
license = {text = "Apache License 2.0"}
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "google-cloud-aiplatform[adk,agent-engines]>=1.93.0",
    "google-genai>=1.9.0",
    "pydantic>=2.10.6",
    "python-dotenv>=1.0.1",
    "google-adk>=1.0.0",
    "fpdf>=1.7.2",
    "pypdf>=5.0.0",
    "streamlit>=1.35.0",
    "reportlab>=4.4.10",
    "google-cloud-dlp>=3.34.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.2",
    "pytest-asyncio>=0.23.7",
    "google-adk[eval]>=1.0.0",
    "nest-asyncio>=1.6.0",
    "agent-starter-pack>=0.14.1",
    "codespell>=2.2.0",
    "types-pyyaml>=6.0.12.20240917",
    "types-requests>=2.32.0.20240914",
]

deployment = [
    "absl-py>=2.2.1",
]



[tool.pytest.ini_options]
pythonpath = "."
asyncio_default_fixture_loop_scope = "function"

[tool.hatch.build.targets.wheel]
# Ensures Hatchling finds the package folder correctly
packages = ["loan_approval_agent"]

[tool.agent-starter-pack]
example_question = "Assess loan for applicant 9813ee1d"

[tool.agent-starter-pack.settings]
agent_directory = "loan_approval_agent"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
