[project]
name = "dlt-agent-v2"
version = "0.1.0"
description = ""
authors = [
    {name = "Brendan Hills",email = "brendanhills@google.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas (>=2.3.0,<3.0.0)",
    "google-adk (>=1.4.1,<2.0.0)",
    "google-genai (>=1.21.0,<2.0.0)"
]

[tool.poetry]
package-mode=false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
