# .streamlit/secrets.toml

# --- Google Cloud Platform Configuration ---
# Replace the placeholder values with your actual GCP details.

[gcp]
project_id = "uk-bh-experiments-argolis"
location = "us-central1"  # e.g., us-central1
bucket_name = "gs://uk-bh-experiments-argolis-us/mclaren/cad"
