# .streamlit/secrets.toml

# --- Google Cloud Platform Configuration ---
# Replace the placeholder values with your actual GCP details.

[gcp]
project_id = "uk-bh-experiments-argolis"
location = "us-central1"  # e.g., us-central1
bucket_name = "gs://uk-bh-experiments-argolis-us/mclaren/cad"

[app]
default_system_instruction = """You are an expert in understanding and interpreting CAD diagrams for car parts for an engineering team. 
Provide very clear and factual output that is suitable for an experienced engineer to understand. 
Use normal mechanical engineering terminology. Be meticulous and careful."""
default_prompt = """You will be provided with a CAD diagram. Your task is to create a checklist for this CAD diagram. 
An engineer will use the checklist to verify all of the dimensions and tolerances are correct in this diagram.
Follow these steps: 

1.  Interpret the CAD diagram: 
    *   Carefully analyze the provided CAD diagram.
    *   Interpret any symbols on the diagram using standard conventions for CAD drawings.
2.  Create a checklist:
    *   Produce a list of dimensions and tolerances, grouped by component, and ordered in a logical way.
    *   It is very important that you don't make any errors with the numbers in the diagram.
    *   If you are unsure of any number, then make that very clear.
3.  Output the checklist."""