[project]
name = "loveholidays"
version = "0.1.0"
description = ""
authors = [
    {name = "Brendan Hills",email = "brendanhills@google.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-cloud-aiplatform (>=1.92.0,<2.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
