[project]
name = "pearson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai (>=1.3.0,<3.0.0)",
    "streamlit (>=1.42.2,<3.0.0)",
    "google-cloud-storage (>=3.1.0,<4.0.0)",
    "ipykernel (>=6.29.5,<7.0.0)",
    "ipython (>=9.0.0,<10.0.0)",
    "moviepy (>=2.1.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.uv.workspace]
members = [
    "speech",
]
