import os
import pandas as pd

os.makedirs("data", exist_ok=True)

# Sample / Seed Risk Register Data based on Google Sheet
risk_data = [
    {
        "ID": "R-0001",
        "Status": "Closed",
        "Risk_Owner": "Michael Maconachie",
        "Driver_Tree_Ref": "Contract Terms",
        "Risk_Name": "Hard coded URL terms",
        "Risk_Description": "Dedicated Contract Manager will be required to support bespoke contract requirements including updates to URL terms.",
        "Cause_Category": "Legal/Contract",
        "Normalized_Category": "Scope",
        "Inherent_Risk": "Medium",
        "Residual_Risk": "Medium",
        "Trend": "Same",
        "Priority": "Not Urgent",
        "Escalation_Status": "Internal",
        "Date_Raised": "2025-11-12",
        "Date_Closed": "2026-02-02",
        "Risk_Last_Updated": "2026-02-02"
    },
    {
        "ID": "R-0002",
        "Status": "Active",
        "Risk_Owner": "Michael Maconachie",
        "Driver_Tree_Ref": "Governance & Compliance",
        "Risk_Name": "Extensive Monaro remediation rights for defects/breaches",
        "Risk_Description": "Remediation rights triggered for defects/breaches due to delivery or cyber security issues.",
        "Cause_Category": "Legal/Contract",
        "Normalized_Category": "Scope",
        "Inherent_Risk": "Low",
        "Residual_Risk": "Very Low",
        "Trend": "Better",
        "Priority": "Not Urgent",
        "Escalation_Status": "Internal",
        "Date_Raised": "2025-11-12",
        "Date_Closed": "",
        "Risk_Last_Updated": "2026-08-01"
    },
    {
        "ID": "R-0003",
        "Status": "Active",
        "Risk_Owner": "Michael Maconachie",
        "Driver_Tree_Ref": "Governance & Compliance",
        "Risk_Name": "Extensive audit rights for Monaro and government bodies (ANAO)",
        "Risk_Description": "Cost of compliance and providing access/info to ANAO within defined boundaries.",
        "Cause_Category": "Legal/Contract",
        "Normalized_Category": "Cost",
        "Inherent_Risk": "High",
        "Residual_Risk": "High",
        "Trend": "Same",
        "Priority": "Not Urgent",
        "Escalation_Status": "Internal",
        "Date_Raised": "2025-11-12",
        "Date_Closed": "",
        "Risk_Last_Updated": "2026-08-02"
    },
    {
        "ID": "R-0004",
        "Status": "Active",
        "Risk_Owner": "Susan Allin",
        "Driver_Tree_Ref": "Schedule 5 Governance",
        "Risk_Name": "Onerous governance and reporting provisions",
        "Risk_Description": "Inefficiency driven by over governance of program.",
        "Cause_Category": "Scope",
        "Normalized_Category": "Scope",
        "Inherent_Risk": "Medium",
        "Residual_Risk": "Medium",
        "Trend": "Same",
        "Priority": "Urgent",
        "Escalation_Status": "IPF/PSG",
        "Date_Raised": "2025-11-12",
        "Date_Closed": "",
        "Risk_Last_Updated": "2026-07-31"
    },
    {
        "ID": "R-0005",
        "Status": "Active",
        "Risk_Owner": "Michael Maconachie",
        "Driver_Tree_Ref": "Policy Compliance",
        "Risk_Name": "Compliance with extensive Commonwealth Policies",
        "Risk_Description": "Passive acceptance of policy changes can increase delivery risk/cost.",
        "Cause_Category": "Legal/Contract",
        "Normalized_Category": "Cost",
        "Inherent_Risk": "Medium",
        "Residual_Risk": "Low",
        "Trend": "Better",
        "Priority": "Prompt",
        "Escalation_Status": "Internal",
        "Date_Raised": "2025-11-12",
        "Date_Closed": "",
        "Risk_Last_Updated": "2026-08-03"
    },
    {
        "ID": "R-0006",
        "Status": "Active",
        "Risk_Owner": "Michael Maconachie",
        "Driver_Tree_Ref": "Personnel Security",
        "Risk_Name": "Individual Confidentiality Deed Polls required for personnel",
        "Risk_Description": "Slow and heavyweight NDA process is slow to onboard Google personnel.",
        "Cause_Category": "Legal/Contract",
        "Normalized_Category": "Schedule",
        "Inherent_Risk": "Medium",
        "Residual_Risk": "Low",
        "Trend": "Better",
        "Priority": "Not Urgent",
        "Escalation_Status": "Internal",
        "Date_Raised": "2025-11-12",
        "Date_Closed": "",
        "Risk_Last_Updated": "2026-08-01"
    },
    {
        "ID": "R-0007",
        "Status": "Active",
        "Risk_Owner": "Susan Allin",
        "Driver_Tree_Ref": "Governance & Compliance",
        "Risk_Name": "Liability - unlimited liability for repudiation and wilful default",
        "Risk_Description": "Material breaches could result in financial and reputational losses.",
        "Cause_Category": "Governance Assurance",
        "Normalized_Category": "Cost",
        "Inherent_Risk": "Critical",
        "Residual_Risk": "Critical",
        "Trend": "Same",
        "Priority": "Urgent",
        "Escalation_Status": "IPF/PSG",
        "Date_Raised": "2025-11-12",
        "Date_Closed": "",
        "Risk_Last_Updated": "2026-08-03"
    },
    {
        "ID": "R-0008",
        "Status": "Active",
        "Risk_Owner": "Michael Maconachie",
        "Driver_Tree_Ref": "Key Personnel",
        "Risk_Name": "Key Personnel commitments and retention",
        "Risk_Description": "Loss of customer confidence and impact on delivery capability.",
        "Cause_Category": "Governance Assurance",
        "Normalized_Category": "Schedule",
        "Inherent_Risk": "Low",
        "Residual_Risk": "Low",
        "Trend": "Same",
        "Priority": "Not Urgent",
        "Escalation_Status": "Internal",
        "Date_Raised": "2025-11-12",
        "Date_Closed": "",
        "Risk_Last_Updated": "2026-07-28"
    }
]

# Sample / Seed Issue Register Data
issue_data = [
    {
        "ID": "I-0001",
        "Status": "Closed",
        "Issue_Owner": "Tom Trobe",
        "Driver_Tree_Ref": "1.10b Platform Ready",
        "Issue_Name": "Platform Ready Test/Dev environment delay",
        "Issue_Description": "Not having a Platform Ready Test/Dev environment delivered by Month 6.5.",
        "Impact_Category": "Schedule",
        "Normalized_Category": "Schedule",
        "Severity_Rating": "High",
        "Trend": "Better",
        "Priority_Rating": "Prompt",
        "Escalate_To": "Google Internal",
        "Date_Raised": "2026-07-01",
        "Date_Closed": "2026-07-30",
        "Last_Updated": "2026-07-30"
    },
    {
        "ID": "I-0003",
        "Status": "Active",
        "Issue_Owner": "Tom Trobe",
        "Driver_Tree_Ref": "1.10c Environment Ready",
        "Issue_Name": "Environment Ready platform config delay",
        "Issue_Description": "Unable to utilize environment to get first use of GDC for build tasks.",
        "Impact_Category": "Schedule",
        "Normalized_Category": "Schedule",
        "Severity_Rating": "Critical",
        "Trend": "Same",
        "Priority_Rating": "Urgent",
        "Escalate_To": "IPF/PSG",
        "Date_Raised": "2026-07-08",
        "Date_Closed": "",
        "Last_Updated": "2026-08-02"
    },
    {
        "ID": "I-0004",
        "Status": "Active",
        "Issue_Owner": "Scott Deacon",
        "Driver_Tree_Ref": "1.10d Mission Support",
        "Issue_Name": "Delayed build of E01 due to product build quality issues",
        "Issue_Description": "Delayed build of E01 resulting in flow-on delays to CD1 delivery.",
        "Impact_Category": "Schedule",
        "Normalized_Category": "Schedule",
        "Severity_Rating": "Critical",
        "Trend": "Worse",
        "Priority_Rating": "Immediate",
        "Escalate_To": "IPF/PSG",
        "Date_Raised": "2026-07-30",
        "Date_Closed": "",
        "Last_Updated": "2026-08-04"
    },
    {
        "ID": "I-0006",
        "Status": "Active",
        "Issue_Owner": "Scott Deacon",
        "Driver_Tree_Ref": "1.17 MSS SIT",
        "Issue_Name": "GCP Environment sandbox access delay",
        "Issue_Description": "ACN unable to utilize GCP environment due to sandbox access issues.",
        "Impact_Category": "Schedule",
        "Normalized_Category": "Schedule",
        "Severity_Rating": "High",
        "Trend": "Better",
        "Priority_Rating": "Prompt",
        "Escalate_To": "Internal",
        "Date_Raised": "2026-07-29",
        "Date_Closed": "",
        "Last_Updated": "2026-08-01"
    },
    {
        "ID": "I-0007",
        "Status": "Active",
        "Issue_Owner": "Tom Trobe",
        "Driver_Tree_Ref": "1.7a DevSecOps",
        "Issue_Name": "DevSecOps Core readiness delay",
        "Issue_Description": "DevSecOps core readiness delayed due to GCP O environment dependency.",
        "Impact_Category": "Schedule",
        "Normalized_Category": "Schedule",
        "Severity_Rating": "Critical",
        "Trend": "Same",
        "Priority_Rating": "Urgent",
        "Escalate_To": "Internal",
        "Date_Raised": "2026-08-01",
        "Date_Closed": "",
        "Last_Updated": "2026-08-03"
    },
    {
        "ID": "I-0011",
        "Status": "Active",
        "Issue_Owner": "Mick Devine",
        "Driver_Tree_Ref": "Export Compliance",
        "Issue_Name": "Lack of dedicated Export Control Officer resource",
        "Issue_Description": "Need for dedicated resource to manage Google-specific export control aspects.",
        "Impact_Category": "Prime Governance",
        "Normalized_Category": "Scope",
        "Severity_Rating": "Critical",
        "Trend": "Worse",
        "Priority_Rating": "Urgent",
        "Escalate_To": "IPF/PSG",
        "Date_Raised": "2026-08-02",
        "Date_Closed": "",
        "Last_Updated": "2026-08-04"
    }
]

pd.DataFrame(risk_data).to_csv("data/risk_register_cache.csv", index=False)
pd.DataFrame(issue_data).to_csv("data/issue_register_cache.csv", index=False)
print("Successfully generated data/risk_register_cache.csv and data/issue_register_cache.csv")
