#!/bin/bash

# ==============================================================================
#
# CORE CONFIGURATION & ENVIRONMENT SETUP
#
# ==============================================================================
# This script is the single source of truth for all environment configuration.
# Running this script will:
#   1. Export the variables for your current shell session.
#   2. Generate `terraform.tfvars` for Terraform.
#   3. Generate `.env` for Python scripts.
#
# To run this script, make it executable and run from your shell:
#   chmod +x config.sh
#   ./config.sh
#
# Other scripts can also 'source' this file to inherit its variables.

# --- Master Configuration Values ---
# Define the core project and location settings here.
export PROJECT_ID="ge-hands-on25tst-101"
export REGION="us-central1"
export LOCATION="us"
# Google Group for Gemini Enterprise end-users.
export GEMINI_END_USERS_GROUP="gemini-enterprise-end-users@googlegroups.com"



# --- File Generation Logic ---
# This section dynamically creates the .env and terraform.tfvars files
# to ensure consistency across all tools.

echo "🚀 Generating configuration files from config.sh..."

# Generate terraform.tfvars
cat > terraform.tfvars << EOL
# Auto-generated from config.sh
# Do not edit this file directly.

project_id = "${PROJECT_ID}"
region     = "${REGION}"
location   = "${LOCATION}"
EOL
echo "✅ terraform.tfvars generated."

# Generate .env file
cat > .env << EOL
# Auto-generated from config.sh
# Do not edit this file directly.

PROJECT_ID="${PROJECT_ID}"
LOCATION="${LOCATION}"
REGION="${REGION}"
GEMINI_END_USERS_GROUP="${GEMINI_END_USERS_GROUP}"
EOL
echo "✅ .env file generated."


# ==============================================================================
#
# SCRIPT-SPECIFIC CONFIGURATION (for setup_env.sh & check_env.sh)
#
# =================================T==============================================

# List of required APIs for the project.
REQUIRED_APIS=(
  "serviceusage.googleapis.com"
  "logging.googleapis.com"
  "cloudresourcemanager.googleapis.com"
  aiplatform.googleapis.com 
  discoveryengine.googleapis.com 
  storage.googleapis.com 
  iam.googleapis.com 
  compute.googleapis.com
)

# Roles for the administrator account running the setup.
ADMIN_ROLES=(
  "roles/storage.admin"
  "roles/discoveryengine.admin"
  "roles/serviceusage.serviceUsageConsumer"
  "roles/logging.viewer"
  "roles/aiplatform.user"
  "roles/iam.serviceAccountAdmin"
)

# End-users to be granted viewer/user access to the Gemini Enterprise application.
GEMINI_USERS=(
    "devstar1012@gcplab.me"
    "devstar1013@gcplab.me"
)

# Roles to be granted to the Gemini Enterprise end-users.
GEMINI_USER_ROLES=(
  "roles/discoveryengine.viewer"
  "roles/discoveryengine.user"
  "roles/aiplatform.user"
)

# Name for the Gemini end-user service account.
GEMINI_END_USER_SA_NAME="gemini-end-user"



echo -e "\nConfiguration complete. Variables are exported for this session."
