import os
import json
import subprocess
from dotenv import load_dotenv

import google.auth
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

def get_terraform_outputs():
    """Gets the terraform outputs as a JSON string."""
    try:
        result = subprocess.run(
            ["terraform", "output", "-json"],
            capture_output=True,
            text=True,
            check=True,
        )
        return json.loads(result.stdout)
    except (subprocess.CalledProcessError, FileNotFoundError, json.JSONDecodeError) as e:
        print(f"Error getting terraform outputs: {e}")
        return None

def print_manual_group_instructions(group_email):
    """Prints instructions for manually creating a Google Group."""
    print("\n--- Manual Step: Create Google Group for End-Users ---")
    print(
        f"The setup requires a Google Group with the email '{group_email}' for managing end-user access."
    )
    print("This script cannot create the group automatically.")
    print("Please create the Google Group manually:")
    print("1. Go to Google Groups: https://groups.google.com/my-groups")
    print("2. Click 'Create group'.")
    print(f"3. Set the 'Group email' to: {group_email.split('@')[0]}")
    print("4. Configure other settings as needed and create the group.")
    print(
        "5. After creating the group, re-run the './setup_env.sh' script to grant the necessary permissions."
    )

def create_google_group(group_email, customer_id):
    """Creates a Google Group using the Cloud Identity API."""
    print(f"\n--- Creating Google Group: {group_email} ---")
    try:
        credentials, _ = google.auth.default(
            scopes=["https://www.googleapis.com/auth/cloud-identity.groups"]
        )
        service = build("cloudidentity", "v1", credentials=credentials)

        group_body = {
            "groupKey": {"id": group_email},
            "parent": f"customers/{customer_id}",
            "displayName": group_email.split("@")[0],
            "description": "A group for Gemini Enterprise end-users",
            "labels": {"cloudidentity.googleapis.com/groups.discussion_forum": ""},
        }

        request = service.groups().create(body=group_body)
        operation = request.execute()

        print(f"Group creation initiated. Operation name: {operation['name']}")
        print("It may take a few moments for the group to become available.")
        print(
            "After the group is created, re-run the './setup_env.sh' script to grant the necessary permissions."
        )

    except HttpError as e:
        if e.resp.status == 409:
            print(f"--- Group '{group_email}' already exists. ---")
        else:
            print(f"An error occurred creating the group: {e}")
            print("Please try creating the group manually in the Google Admin console.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        print("Please try creating the group manually in the Google Admin console.")

def get_customer_id():
    """Gets the Google Workspace Customer ID."""
    try:
        result = subprocess.run(
            ["gcloud", "organizations", "list", "--format=json"],
            capture_output=True,
            text=True,
            check=True,
        )
        orgs = json.loads(result.stdout)
        if orgs and "directoryCustomerId" in orgs[0]:
            return orgs[0]["directoryCustomerId"]
        print("Could not find directoryCustomerId in gcloud output.")
        return None
    except (subprocess.CalledProcessError, FileNotFoundError, json.JSONDecodeError, IndexError) as e:
        print(f"Error getting customer ID: {e}")
        return None

def main():
    """Main function to run the setup steps."""
    # Load environment variables and check for required values.
    # If the .env file is missing or outdated, this will guide the user.
    load_dotenv()
    required_vars = ["LOCATION", "GEMINI_END_USERS_GROUP"]
    missing_vars = [var for var in required_vars if not os.environ.get(var)]

    if missing_vars:
        print(f"🚨 Missing required environment variables: {', '.join(missing_vars)}")
        print("   These are loaded from the '.env' file, which is generated by 'config.sh'.")
        print(
            "\n   Please run or re-run the configuration script to create/update your '.env' file: ./config.sh\n"
        )
        return

    location = os.environ.get("LOCATION")
    gemini_end_users_group = os.environ.get("GEMINI_END_USERS_GROUP")

    outputs = get_terraform_outputs()
    if not outputs:
        return

    search_engine_id = outputs.get("search_engine_id", {}).get("value")
    if not search_engine_id:
        print("Could not find 'search_engine_id' in terraform outputs.")
        return

    customer_id = get_customer_id()
    if not customer_id:
        print("Could not retrieve Google Workspace Customer ID. Cannot create group automatically.")
        print_manual_group_instructions(gemini_end_users_group)
        return

    print("--- Manual Step: Configure Identity Provider (IdP) ---")
    print(
        "To set up the Identity Provider for your Gemini Enterprise app (required for Google Drive and Gmail data stores):"
    )
    print("1. Go to:")
    print(
        f"https://console.cloud.google.com/gemini-enterprise/locations/{location}/engines/{search_engine_id}/overview/identity?orgonly=true&walkthrough_id=gemini-enterprise--identity-v1--create--quickstart"
    )
    print("2. Follow the on-screen instructions to configure the IdP.")

    create_google_group(gemini_end_users_group, customer_id)
    

if __name__ == "__main__":
    main()
