[project]
name = "ge-handson"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "google-api-python-client>=2.0.0",
    "google-api-core>=2.28.1",
    "google-auth>=2.0.0",
    "google-cloud-discoveryengine>=0.16.0",
    "google-cloud-storage>=2.0.0",
]
